spring:
  data:
    neo4j:
      uri: http://localhost:7474
      username: neo4j
      password: qq1995912qq
  servlet:
    multipart:
      max-file-size: 4MB

application:
  file:
    baseStaticResourcesPath: /caohui/static
